### ISSUE TITLE
[auth-mailchimp-sync] Import existing users

### ISSUE THREAD

**Issue by dackers86** [mailchimp/Firebase#25] opened 2021-11-24 10:13 UTC
Original feature request https://github.com/firebase/extensions/issues/637

**Comment by eduferfer** [comment] 2021-11-24 12:15
@dackers86 thanks for taking care!

**Comment by barticus** [comment] 2022-05-17 05:28
Duplicate of https://github.com/mailchimp/Firebase/issues/29, closing.

**Closed by barticus** 2022-05-17 05:28 UTC
